import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Truck, Warehouse, Banknote, Award, Plane, Network, Download, Clock, AlertTriangle, ClipboardCheck, Package, Info, CheckCircle } from 'lucide-react';
import { getMonitoring } from '../../../services/admin/monitoring.service.js';
import './AdminMonitoring.css';

const money = value => new Intl.NumberFormat('en-IE', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(value);
const quantity = value => new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 1 }).format(value);
const dateTime = value => new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(value));

function Pending({ children, reason, dark = false }) {
  return <span className="lm-pending" tabIndex={0} aria-label={reason}><button type="button" disabled className={`lm-button ${dark ? 'lm-dark' : ''}`}>{children}</button><span role="tooltip">{reason}</span></span>;
}

export default function AdminMonitoring() {
  const [query, setQuery] = useState({ period: 'all', status: '' });
  const [state, setState] = useState({ data: null, loading: true, error: '' });
  const [expanded, setExpanded] = useState(false);
  const [retry, setRetry] = useState(0);
  useEffect(() => {
    let cancelled = false;
    getMonitoring(query).then(data => { if (!cancelled) setState({ data, loading: false, error: '' }); }).catch(error => { if (!cancelled) setState({ data: null, loading: false, error: error.message }); });
    return () => { cancelled = true; };
  }, [query, retry]);
  function update(values) { setState(previous => ({ ...previous, loading: true, error: '' })); setQuery(previous => ({ ...previous, ...values })); setExpanded(false); }
  const data = state.data;
  const rows = data ? expanded ? data.orders : data.orders.slice(0, 3) : [];
  return <div className="lm-page">
    <p className="lm-eyebrow">TRUNG TÂM KIỂM SOÁT <span>• ĐƠN HÀNG & CHUỖI CUNG ỨNG LIÊN HUB</span></p>
    <section className="lm-heading"><div><h1>Giám Sát Đơn Hàng & Tồn Kho Toàn Hệ Thống</h1><p>Giám sát đơn hàng, dung tích kho và vật tư cần theo dõi trong không gian LUMORA.</p></div><div className="lm-toolbar"><label><Clock size={15} />Ngày tạo đơn:<select aria-label="Khoảng thời gian theo ngày tạo đơn" value={query.period} onChange={event => update({ period: event.target.value })}><option value="all">Tất cả</option><option value="today">Hôm nay</option><option value="7d">7 ngày</option><option value="30d">30 ngày</option></select></label><Pending reason="Chưa có nguồn và định nghĩa báo cáo SLA"><Download size={15} />Tải báo cáo kiểm soát SLA</Pending><span className="lm-incident">Cảnh báo sự cố: Chưa tích hợp</span></div></section>
    {state.error ? <section className="lm-state" role="alert"><h2>Không thể tải dữ liệu giám sát</h2><p>{state.error}</p><button className="lm-button" onClick={() => { setState({ data: null, loading: true, error: '' }); setRetry(value => value + 1); }}>Thử lại</button></section> : !data ? <div className="lm-state" role="status">Đang tải dữ liệu demo…<div className="lm-skeleton" /></div> : <>
      <p className="lm-demo-note"><b>Dữ liệu demo</b> Mốc cố định: {data.referenceDate} (UTC+07:00). Hôm nay, 7 ngày và 30 ngày đều kết thúc tại mốc này. Không có realtime hoặc đồng bộ Backend.</p>
      <section className="lm-kpis" aria-label="Tổng quan giám sát"><article className="lm-card"><div className="lm-kpi-label">TỔNG GIÁ TRỊ ĐANG CHẠY<Banknote size={22} /></div><strong>{money(data.runningValue)}</strong><p>Đơn chưa hoàn tất trong kỳ chọn.</p><small>Tăng trưởng: Chưa tích hợp</small></article><article className="lm-card"><div className="lm-kpi-label">ĐƠN VIP SOVEREIGN<Award size={22} /></div><strong className="lm-unknown">Chưa tích hợp</strong><p>Chưa có tiêu chí phân hạng VIP.</p></article><article className="lm-card"><div className="lm-kpi-label">TUÂN THỦ VẬN CHUYỂN<Plane size={22} /></div><strong className="lm-unknown">Chưa tích hợp</strong><p>Chưa có thời hạn cam kết và dữ liệu SLA.</p></article><article className="lm-card lm-capacity"><div className="lm-kpi-label">TẢI KHO TRUNG CHUYỂN<Network size={22} /></div><strong>{quantity(data.usagePercent)}%</strong><p>{quantity(data.occupiedM3)} / {quantity(data.capacityM3)} m³</p><small>Tổng dung tích sử dụng / tổng sức chứa demo.</small></article></section>
      <section className="lm-orders" aria-busy={state.loading}><header className="lm-section-heading"><h2><Truck size={23} />Live Order Monitoring Deck</h2><span className="lm-pill">Dữ liệu demo • Không realtime</span></header><p className="lm-explanation">Tab đếm theo kỳ đã chọn. “Tất cả” bao gồm đơn hoàn tất; KPI giá trị đang chạy không đổi khi chuyển tab.</p><div className="lm-tabs" role="group" aria-label="Trạng thái đơn hàng"><button aria-pressed={!query.status} className={!query.status ? 'lm-active' : ''} onClick={() => update({ status: '' })}>Tất cả đơn hàng <b>{data.totalOrders}</b></button>{data.statuses.map(status => <button key={status.id} aria-pressed={query.status === status.id} className={query.status === status.id ? 'lm-active' : ''} onClick={() => update({ status: status.id })}>{status.label}<b>{status.count}</b></button>)}</div>
        <div className="lm-order-box">{state.loading ? <div className="lm-state" role="status">Đang lọc đơn hàng…<div className="lm-skeleton" /></div> : rows.length ? <div className="lm-table-scroll" tabIndex={0} aria-label="Bảng giám sát đơn hàng, cuộn ngang khi cần"><table className="lm-table lm-order-table"><thead><tr>{['MÃ ĐƠN / THỜI GIAN', 'KHÁCH HÀNG', 'CẤU KIỆN NGHỆ THUẬT', 'TRỊ GIÁ', 'HUB ĐIỀU PHỐI', 'TRẠNG THÁI VẬN HÀNH', 'GHI CHÚ KỸ THUẬT'].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(order => <tr key={order.id}><td><Link className="lm-order-id" to={"/admin/orders/" + encodeURIComponent(order.id)}>#{order.id}</Link><small>{dateTime(order.createdAt)}</small></td><td><div className="lm-customer"><span aria-hidden="true">{order.customer.split(' ').slice(0, 2).map(word => word[0]).join('')}</span><strong>{order.customer}</strong></div></td><td><div className="lm-item"><span className="lm-image-placeholder" role="img" aria-label="Chưa có ảnh sản phẩm gốc"><Package size={22} /></span><div>{order.itemName}<small>{order.materials}</small></div></div></td><td className="lm-money">{money(order.total)}</td><td>{order.warehouse.name}</td><td><span className={`lm-status lm-status-${order.status}`}>{data.statuses.find(status => status.id === order.status).label}</span></td><td><span className="lm-note">{order.note}</span></td></tr>)}</tbody></table></div> : <div className="lm-state" role="status"><Package size={30} /><h3>Không có đơn hàng phù hợp</h3><p>Thử chọn kỳ khác hoặc tab Tất cả đơn hàng.</p><button className="lm-button" onClick={() => update({ period: 'all', status: '' })}>Xóa bộ lọc</button></div>}
          <footer className="lm-order-footer"><span aria-live="polite">{state.loading ? 'Đang tải…' : `Hiển thị ${rows.length} trên ${data.orders.length} đơn phù hợp • Tổng ${money(data.filteredValue)}`}</span>{data.orders.length > 3 && <button disabled={state.loading} aria-expanded={expanded} onClick={() => setExpanded(value => !value)}>{expanded ? 'Thu gọn danh sách ↑' : 'Xem tất cả danh sách đơn hàng →'}</button>}</footer>
        </div>
      </section>
      <section className="lm-inventory"><header className="lm-section-heading"><h2><Warehouse size={23} />Global Multi-Hub Inventory Monitoring</h2><span className="lm-pill">Snapshot demo</span></header><p className="lm-explanation">Dữ liệu kho và vật tư là snapshot cố định, không thay đổi theo bộ lọc ngày tạo đơn. Cảnh báo khi lượng vật tư nhỏ hơn hoặc bằng ngưỡng.</p><div className="lm-warehouse-grid">{data.warehouses.map((warehouse, index) => <article className="lm-card" key={warehouse.id}><header><h3>{index + 1}. {warehouse.name}</h3><span className={`lm-stock-badge ${warehouse.lowStockCount ? 'lm-stock-alert' : ''}`}>{warehouse.lowStockCount ? 'CẢNH BÁO VẬT TƯ' : 'CHƯA CÓ CẢNH BÁO TRONG FIXTURE'}</span></header><p className="lm-warehouse-description">{warehouse.description}</p><dl><div><dt>Lưu kho:</dt><dd>{quantity(warehouse.finishedPackages)} kiện thành phẩm</dd></div><div><dt>Tổng giá trị:</dt><dd className="lm-muted">Chưa tích hợp</dd></div><div><dt>Dung tích sử dụng:</dt><dd>{quantity(warehouse.usagePercent)}%</dd></div></dl><div className="lm-progress" role="meter" aria-label={`Dung tích ${warehouse.name}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={warehouse.usagePercent}><span style={{ width: `${warehouse.usagePercent}%` }} /></div><small>{quantity(warehouse.occupiedM3)} / {quantity(warehouse.capacityM3)} m³</small><div className="lm-warehouse-alert">{warehouse.lowStockCount ? <AlertTriangle size={18} /> : <CheckCircle size={18} />}<span>{warehouse.lowStockCount ? `${warehouse.lowStockCount} vật tư chạm ngưỡng trong fixture` : 'Không có vật tư chạm ngưỡng trong fixture'}</span></div></article>)}</div></section>
      <section className="lm-card lm-watchlist"><header><div className="lm-watchlist-title"><span><ClipboardCheck size={26} /></span><div><h2>Critical Material Low-Stock Watchlist</h2><p>Vật tư dưới hoặc bằng ngưỡng dự trữ • {data.lowStock.length} kết quả demo</p></div></div><span className="lm-pill">Đồng bộ mỏ đá & xưởng cưa: Chưa tích hợp</span></header>{data.lowStock.length ? <div className="lm-table-scroll" tabIndex={0} aria-label="Danh sách vật tư cần theo dõi, cuộn ngang khi cần"><table className="lm-table lm-material-table"><thead><tr>{['CHỦNG LOẠI / MÃ VẬT LIỆU', 'VỊ TRÍ LƯU KHO', 'MỨC TỒN / NGƯỠNG', 'THỜI GIAN CUNG ỨNG', 'TÁC ĐỘNG SẢN XUẤT', 'LỆNH CAN THIỆP'].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{data.lowStock.map(material => <tr key={material.id}><td><div className="lm-material-name"><Package size={24} /><div><strong>{material.name}</strong><small>SKU: {material.sku}</small></div></div></td><td>{material.warehouse.name}<small>{material.location}</small></td><td><div className="lm-stock-values"><strong>{quantity(material.quantity)} {material.unit}</strong><span>/ Tối thiểu {quantity(material.threshold)} {material.unit}</span></div><div className="lm-progress"><span style={{ width: `${Math.min(100, material.quantity / material.threshold * 100)}%` }} /></div></td><td>{material.leadDays} ngày<small>{material.supplier} (demo)</small></td><td><span className="lm-impact">{material.impact}</span></td><td><Pending dark reason="Đặt hàng khẩn cấp thuộc nghiệp vụ mua/nhập hàng, Admin chỉ giám sát">Kích hoạt đặt hàng khẩn cấp</Pending></td></tr>)}</tbody></table></div> : <p className="lm-state">Không có vật tư chạm ngưỡng trong fixture.</p>}<p className="lm-explanation"><Info size={13} />Số lượng chỉ so sánh với ngưỡng của cùng vật tư, cùng đơn vị; không cộng khối, m³ và kg với nhau.</p></section>
    </>}
  </div>;
}
